{{- if not .Values.credentials.existingSecret }}
{{- if or .Values.credentials.clientId .Values.credentials.clientSecret .Values.credentials.refreshToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-fulfillment.credentialsSecretName" . }}
  labels:
    {{- include "network-fulfillment.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.credentials.clientId }}
  NETWORK_CLIENT_ID: {{ .Values.credentials.clientId | quote }}
  {{- end }}
  {{- if .Values.credentials.clientSecret }}
  NETWORK_CLIENT_SECRET: {{ .Values.credentials.clientSecret | quote }}
  {{- end }}
  {{- if .Values.credentials.refreshToken }}
  NETWORK_REFRESH_TOKEN: {{ .Values.credentials.refreshToken | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and .Values.database.url (not .Values.database.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "network-fulfillment.databaseSecretName" . }}
  labels:
    {{- include "network-fulfillment.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
